/**
 * Download the latin subset of the site's three typefaces from Google Fonts and
 * emit assets/fonts.css plus assets/fonts/*.woff2.
 *
 * Self-hosting means the Content-Security-Policy does not have to allow
 * fonts.googleapis.com or fonts.gstatic.com, visitors' IP addresses are not sent
 * to Google on every page load, and the intermittent 404s Google's own CDN
 * serves for these files stop reaching our users.
 *
 * Re-run after changing which weights the site uses:
 *   node tools/fetch-fonts.mjs
 */
import fs from 'node:fs';
import path from 'node:path';
import crypto from 'node:crypto';

const REPO = path.resolve(import.meta.dirname, '..');
const OUT_DIR = path.join(REPO, 'assets/fonts');

// Ask as a modern browser so Google returns woff2 rather than older formats.
const UA = 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 '
         + '(KHTML, like Gecko) Chrome/151.0.0.0 Safari/537.36';

const CSS_URL = 'https://fonts.googleapis.com/css2'
  + '?family=Instrument+Serif:ital,wght@0,400;1,400'
  + '&family=DM+Sans:ital,opsz,wght@0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;1,9..40,400'
  + '&family=JetBrains+Mono:wght@400;500;700'
  + '&display=swap';

const css = await fetch(CSS_URL, { headers: { 'User-Agent': UA } }).then(r => {
  if (!r.ok) throw new Error(`Google Fonts returned ${r.status}`);
  return r.text();
});

// Keep only the latin block of each face. The site is English-only; the other
// subsets (cyrillic, greek, vietnamese…) are dead weight.
const faces = [];
for (const chunk of css.split('@font-face').slice(1)) {
  if (!chunk.includes('U+0000-00FF')) continue;
  const grab = (re) => (chunk.match(re) || [])[1];
  faces.push({
    family: grab(/font-family:\s*'([^']+)'/),
    style:  grab(/font-style:\s*(\w+)/) || 'normal',
    weight: (grab(/font-weight:\s*([\d\s]+)/) || '400').trim(),
    url:    grab(/url\((https:\/\/fonts\.gstatic\.com\/[^)]+)\)/),
    range:  grab(/unicode-range:\s*([^;]+)/),
  });
}
if (!faces.length) throw new Error('no latin faces found — did the CSS format change?');

fs.mkdirSync(OUT_DIR, { recursive: true });

// Google serves one variable file per requested weight, so the same bytes come
// back several times. Hash the payload and write each distinct file once.
const byHash = new Map();
const written = [];

for (const face of faces) {
  const buf = Buffer.from(await fetch(face.url, { headers: { 'User-Agent': UA } })
    .then(r => {
      if (!r.ok) throw new Error(`${face.family} ${face.style} ${face.weight}: ${r.status}`);
      return r.arrayBuffer();
    }));

  const hash = crypto.createHash('sha256').update(buf).digest('hex').slice(0, 8);
  let file = byHash.get(hash);
  if (!file) {
    const slug = face.family.toLowerCase().replace(/\s+/g, '-');
    file = `${slug}-${face.style}-${hash}.woff2`;
    fs.writeFileSync(path.join(OUT_DIR, file), buf);
    byHash.set(hash, file);
    written.push({ file, bytes: buf.length });
  }
  face.file = file;
}

const rules = faces.map(f => `@font-face {
  font-family: '${f.family}';
  font-style: ${f.style};
  font-weight: ${f.weight};
  font-display: swap;
  src: url('fonts/${f.file}') format('woff2');
  unicode-range: ${f.range};
}`).join('\n\n');

const total = written.reduce((n, w) => n + w.bytes, 0);

fs.writeFileSync(path.join(REPO, 'assets/fonts.css'), `/*!
 * Self-hosted webfonts — latin subset only.
 *
 * Generated by tools/fetch-fonts.mjs from Google Fonts. Serving these ourselves
 * keeps fonts.googleapis.com and fonts.gstatic.com out of the CSP, stops every
 * visitor's IP reaching Google, and removes two render-blocking cross-origin
 * requests per page.
 *
 * Fonts are licensed under the SIL Open Font License 1.1:
 *   Instrument Serif  https://fonts.google.com/specimen/Instrument+Serif
 *   DM Sans           https://fonts.google.com/specimen/DM+Sans
 *   JetBrains Mono    https://fonts.google.com/specimen/JetBrains+Mono
 *
 * Do not hand-edit. Re-run: node tools/fetch-fonts.mjs
 */

${rules}
`);

console.log(`${faces.length} faces -> ${written.length} unique files, ${(total / 1024).toFixed(0)} KB total`);
written.forEach(w => console.log(`  ${w.file.padEnd(44)} ${(w.bytes / 1024).toFixed(1)} KB`));
console.log('\nwrote assets/fonts.css');
